### ISSUE TITLE
Null pointer when choosing "Options" at menu

### ISSUE THREAD

**Issue by Kexus** [Vikare/Archon#6]
Choosing Options (3) on the menu causes a null pointer exception.

    Exception in thread "main" java.lang.NullPointerException
        at engine.Game.run(Game.java:118)
        at Archon.main(Archon.java:28)

**Comment by Vikare** [comment]
Options (3) and Credits (4) rest the game state to "default" before returning to the main loop, ensuring that the game does not continue without a player or map being generated.
