### ISSUE TITLE
IndexOutOfBoundsException when targeting enemy outside of array size

### ISSUE THREAD

**Issue by Vikare** [Vikare/Archon#9]
Targeting an index that is beyond than the number of enemies in a room throws an  Index Out Of Bounds Exception.

    Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
            at java.util.ArrayList.rangeCheck(UnknownSource)
            at java.util.ArrayList.get(Unknown Source)
            at environment.Room.getEntityFromIndex(Room.java:164)
            at engine.Utility.parseCommand(Utility.java:118)
            at engine.Game.runCombat(Game.java:148)
            at engine.Game.run(Game.java:124)
            at Archon.main(Archon.java:28)

**Comment by Vikare** [comment]
try catches for IndexOutOfBounds have been added for all targeted commands. It will prompt the user for a valid target index after handling the error.
